[stations]
selected_profile = "Central_LAG"

[stations.profiles.Swanwick_Military]
include = [
    "EGDR_*",
    "EGDO_*",
    "EGDI_*",
    "EGDY_*",
    "EGDM_*",
    "EGVP_*",
    "EGVO_*",
    "EGUB_*",
    "EGWU_*",
    "EGVA_*",
    "EGVN_*",
    "EGUW_*",
    "EGOS_*",
    "EGOE_*",
    "EGOV_*",
    "EGOQ_*",
    "EGNO_*",
    "EGUL_*",
    "EGUN_*",
    "EGYM_*",
    "EGXT_*",
    "EGXC_*",
    "EGYD_*",
    "EGYE_*",
    "EGXE_*",
    "EGXZ_*",
    "EGQL_*",
    "EGQS_*",
    "EGVV_*",
    "MAN_*",
    "LON_*",
    "STC_*",
    "SCO_*",
    "LTC_*",
    "LON_SC*",
    "*_FMP",
]
exclude = []
priority = [
    "*_FMP",
    "*_CTR",
    "*_APP",
    "*_TWR",
    "*_GND",
    "*_DEL",
]
frequencies = "HideAliased"
grouping = "None"

[stations.profiles.Swanwick_Military.aliases]

[stations.profiles.Default]
include = []
exclude = []
priority = [
    "*_FMP",
    "*_CTR",
    "*_APP",
    "*_TWR",
    "*_GND",
    "*_DEL",
]

[stations.profiles.Default.aliases]

[stations.profiles.South_LAG]
include = [    
    "SOLENT*",
    "THAMES*",
    "*_FMP",
    "EGHH_*",
    "EGHI_*",
    "EGKA_*",
    "EGKK_*",
    "EGLF_*",
    "EGKB_*",
    "EGMD_*",
    "EGMC_*",
    "EGLC_*",
    "EGLL_*",
    "LON_D*",
    "LON_W*",
    "LON_C*",
    "LON_M*",
    "LON_E*",
    "LON_SC*",
    "LON_S*",
    "LON_23*",
    "LTC_*",
    "EGJJ_*",
    "EDYY_K*",
    "EDYY_N*",
    "EBBU_*",
    "PAR_*",
    "LFEE_*",
    "LFRR_*",
    "LFQQ_*APP",
    "LFRN_*APP",
    "EGVV_*",

]
exclude = []
priority = [
    "*_FMP",
    "*_CTR",
    "*_APP",
    "*_TWR",
    "*_GND",
    "*_DEL",
]
frequencies = "HideAliased"
grouping = "None"

[stations.profiles.South_LAG.aliases]

"135.805" = "TC BBX"
"119.730" = "LL INT N"
"122.780" = "LF AIR"
"120.230" = "SOLENT"
"133.005" = "LFEE"
"134.355" = "LF APC"
"136.600" = "LFRR E"
"124.230" = "KK AIR"
"128.155" = "LFFF"
"134.980" = "LL INT S"
"125.605" = "HH AIR"
"121.030" = "TC MIDS"
"135.410" = "LFFF LOW"
"129.430" = "AC WOR"
"135.980" = "MAAS NIK"
"121.280" = "TC NW"
"122.730" = "HI RAD"
"128.965" = "MC DIR"
"120.025" = "AC DTY"
"118.565" = "LFRR V"
"118.825" = "TC NE"
"119.780" = "TC N"
"129.405" = "KB APP"
"118.480" = "AC CLN"
"128.805" = "BRU N"
"118.080" = "LC AIR"
"125.500" = "LFRR"
"126.825" = "KK INT"
"119.480" = "HH RAD"
"126.480" = "LFQQ"
"118.505" = "LL AIR S"
"127.385" = "LFRR J"
"121.230" = "TC EAST"
"134.755" = "AC S23"
"132.505" = "LFEE NOR"
"126.080" = "AC WST"
"120.530" = "TC SE"
"132.700" = "TC TMS"
"118.205" = "HI AIR"
"133.180" = "TC SW"
"127.730" = "MC AIR"
"134.905" = "AC DVR"
"129.505" = "LFRR W"
"135.255" = "AC BCN"
"129.575" = "BRU E"
"128.025" = "LC DIR"
"132.205" = "MAAS KOK"
"127.830" = "AC BBX"
"132.605" = "AC SC BBX"
"125.980" = "MAAS BRU"
"127.105" = "AC CEN"
"128.815" = "AC BHD"
"134.430" = "PC SE"
"125.205" = "JJ CTL"
"131.100" = "BRU W"
"134.000" = "LFRN"
"134.125" = "TC S"

[stations.profiles.Central_LAG]
include = [
    "EGSS_*",
    "EGGW_*",
    "EGSC_*",
    "ESSEX*",
    "EGTK_*",
    "EGTC_*",
    "EGBB_*",
    "EGNX_*",
    "EGLL_N*APP",
    "EGLC_*",
    "EGMC_*",
    "MAN_*",
    "LON_S*",
    "LON_SC*",
    "LON_D*",
    "LON_N*",
    "LON_W*",
    "LTC_*",
    "EDYY_D*",
    "EDYY_K*",
    "EDYY_N*",
    "EBBU_*",
    "EHAA_*",
    "EGVV_*",
    "*_FMP",
]
exclude = []
priority = [
    "*_FMP",
    "*_CTR",
    "*_APP",
    "*_TWR",
    "*_GND",
    "*_DEL",
]
frequencies = "HideAliased"
grouping = "None"
[stations.profiles.Central_LAG.aliases]

"135.715" = "PC NE"
"118.480" = "AC CLN"
"118.080" = "LC AIR"
"133.800" = "PC E"
"132.205" = "MAAS KOK"
"118.305" = "BB AIR"
"129.550" = "GW INT"
"120.530" = "TC SE"
"127.730" = "MC AIR"
"123.705" = "AMS WEST"
"127.830" = "AC BBX"
"124.005" = "NX AIR"
"120.025" = "AC DTY"
"120.625" = "SS INT"
"135.580" = "AC LKS"
"125.750" = "AMS LOW"
"132.605" = "AC SC BBX"
"132.555" = "GW AIR"
"128.965" = "MC DIR"
"119.730" = "LL INT N"
"126.180" = "NX APC"
"127.105" = "AC CEN"
"135.805" = "TC BBX"
"134.905" = "AC DVR"
"134.430" = "PC SE"
"135.980" = "MAAS NIK"
"121.030" = "TC MIDS"
"132.700" = "TC TMS"
"121.230" = "TC EAST"
"123.980" = "BB INT"
"135.960" = "MAAS DELTA"
"134.125" = "TC S"
"133.180" = "TC SW"
"133.200" = "MPC BBX"
"129.575" = "BRU E"
"121.280" = "TC NW"
"128.805" = "BRU N"
"129.430" = "AC WOR"
"123.800" = "SS AIR"
"133.705" = "AC NTH"
"128.130" = "AC NOR"
"134.375" = "AMS ALL"
"131.100" = "BRU W"
"128.025" = "LC DIR"
"119.780" = "TC N"
"125.980" = "MAAS BRU"
"118.825" = "TC NE"


[stations.profiles.UK_ALL]
include = [
    "EG*",
    "NAT_*",
    "LON_*",
    "LTC_*",
    "SCO_*",
    "STC_*",
    "MAN_*",
    "UK_*",
    "*_FMP",
]
exclude = []
priority = [
    "*_FMP",
    "*_CTR",
    "*_APP",
    "*_TWR",
    "*_GND",
    "*_DEL",
]
frequencies = "HideAliased"
grouping = "None"

[stations.profiles.UK_ALL.aliases]

[stations.profiles.West_LAG]
include = [
    "EGHE_*",
    "EGHC_*",
    "EGHG_*",
    "EGHQ_*",
    "EGTE_*",
    "EGHQ_*",
    "EGFF_*",
    "EGSY_*",
    "EGGD_*",
    "EGBJ_*",
    "EGBC_*",
    "EGJB_*",
    "EGJA_*",
    "EGJJ_*",
    "MAN_*",
    "LON_*",
    "LTC_*",
    "EGVV_*",
    "NAT*",
    "EGGX*",
    "*_FMP",
]
exclude = []

priority = [
    "*_FMP",
    "*_CTR",
    "*_APP",
    "*_TWR",
    "*_GND",
    "*_DEL",
]
frequencies = "HideAliased"
grouping = "None"

[stations.profiles.West_LAG.aliases]

"133.200" = "PC BBX"
"128.055" = "PC W"

"133.705" = "AC NTH"
"135.580" = "AC LKS"
"120.025" = "AC DTY"
"127.105" = "AC CEN"
"132.605" = "AC SC BBX"
"129.430" = "AC WOR"

"121.030" = "TC MIDS"
"134.125" = "TC S"
"133.180" = "TC SW"
"135.805" = "TC BBX"


[stations.profiles.North_LAG]
include = [
    "EGCC_*",
    "EGGP_*",
    "EGNM_*",
    "EGNJ_*",
    "EGNT_*",
    "EGNV_*",
    "EGNS_*",
    "EGNR_*",
    "EGNH_*",
    "EGSH_*",
    "EDYY_D*",
    "EHAA_*",
    "EIDW_U*",
    "EIDW_L*",
    "EISN_E*",
    "MAN_*",
    "LON_C*",
    "LON_SC*",
    "LON_E*",
    "LON_W*",
    "LTC_M*",
    "LTC_E*",
    "STC_*",
    "SCO_*",
    "EGVV_*",
    "*_FMP",
]
exclude = []
priority = [
    "*_FMP",
    "*_CTR",
    "*_APP",
    "*_TWR",
    "*_GND",
    "*_DEL",
]
frequencies = "HideAliased"
grouping = "None"

[stations.profiles.North_LAG.aliases]

"118.580" = "CC INT S"
"135.005" = "CC INT N"
"121.355" = "CC FIN"
"118.630" = "CC AIR 1"
"119.405" = "CC AIR 2"
"119.855" = "GP RAD 1"
"118.455" = "GP FIN"
"126.355" = "GP AIR"
"134.580" = "NM RAD"
"120.305" = "NM AIR"
"119.130" = "NJ RAD"
"124.905" = "NJ AIR"
"124.380" = "NT RAD 1"
"119.705" = "NT AIR"
"119.005" = "NS ADC"
"135.905" = "NS RAD 1"
"120.855" = "NS RAD 2"
"124.955" = "NR ADC"
"120.055" = "NR RAD"
"130.015" = "NR FIN"
"119.955" = "NH APP"
"118.405" = "NH ADC"
"124.225" = "SH ADC"
"119.355" = "SH RAD"
"128.330" = "SH DIR"

"133.705" = "AC NTH"
"128.130" = "AC NOR"
"135.580" = "AC LKS"
"120.025" = "AC DTY"
"127.105" = "AC CEN"
"132.605" = "AC SC BBX"

"121.030" = "TC MIDS"

"133.200" = "PC BBX"
"133.800" = "PC E"
"135.715" = "PC NE"
"134.430" = "PC SE"
"128.055" = "PC W"

"129.100" = "ScAC Rat"
"132.730" = "ScAc W"
"133.875" = "ScAc WD"
"135.530" = "ScAc BBX"
"134.775" = "ScAc S"
"121.325" = "ScAc E"

"126.300" = "STC BBX"
"123.775" = "STC A"
"130.975" = "STC E"
"124.825" = "STC W"

[stations.profiles.Scottish]
include = [
    "EGAA_*",
    "EGAC_*",
    "EGAE_*",
    "EGPH_*",
    "EGPF_*",
    "EGPK_*",
    "EGPE_*",
    "EGPD_*",
    "EGPB_*",
    "EGPO_*",
    "EGPL_*",
    "EGPC_*",
    "EGPN_*",
    "EGPA_*",
    "MAN_*",
    "LON_N*",
    "STC_*",
    "SCO_*",
    "EGVV_*",
    "NAT*",
    "EGGX*",
    "*_FMP",
]
exclude = []
priority = [
    "*_FMP",
    "*_CTR",
    "*_APP",
    "*_TWR",
    "*_GND",
    "*_DEL",
]
frequencies = "HideAliased"
grouping = "None"

[stations.profiles.Scottish.aliases]

"133.705" = "AC NTH"
"128.130" = "AC NOR"
"135.580" = "AC LKS"

"133.200" = "PC BBX"
"133.800" = "PC E"
"135.715" = "PC NE"
"134.430" = "PC SE"
"128.055" = "PC W"

"129.100" = "ScAC Rat"
"132.730" = "ScAc W"
"133.875" = "ScAc WD"
"135.530" = "ScAc BBX"
"134.775" = "ScAc S"
"121.325" = "ScAc E"

"126.300" = "STC BBX"
"123.775" = "STC A"
"130.975" = "STC E"
"124.825" = "STC W"


[stations.profiles.AFIS_AGCS_Stations]

include = [
"EG**_I*",
"EG**_R*",
"LON*",
"LTC*",
"SCO*",
"STC*",
]

exclude = []
priority = [
    "*_FMP",
    "*_CTR",
    "*_APP",
    "*_TWR",
    "*_GND",
    "*_DEL",
]
frequencies = "HideAliased"
grouping = "None"