# Updates IDs of profiles
#
# Triggered by:
# push to main (by a non bot)

name: Update vATIS Serial

on:
  push:
    branches:
      - 'main'
    paths:
      - '_vATIS/**'

jobs:
  update:
    if: ${{ !contains(github.event.head_commit.message, '[VUK] Update profiles') }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # token: ${{ secrets.VATSIM_UK_GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Get list of changed files
        id: changed_files
        run: |
          CURRENT_SHA=${{ github.sha }}
          PREVIOUS_SHA=$(git rev-parse $CURRENT_SHA^)
          git diff --name-only $PREVIOUS_SHA $CURRENT_SHA > changed_files.txt
          cat changed_files.txt

      - name: Run update script
        id: update
        run: |
          python workflows/vATIS/update.py --changed-files-list changed_files.txt

      - name: Commit and push changes
        run: |
          git config --global user.name 'VATSIM UK'
          git config --global user.email 'privileged-access@vatsim.uk'
          rm changed_files.txt
          git add .
          git commit -m '[VUK] Update profiles'
          git push
